CREATE TABLE IF NOT EXISTS app_user (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  open_id VARCHAR(64) NOT NULL UNIQUE,
  union_id VARCHAR(64) DEFAULT NULL,
  nickname VARCHAR(64) DEFAULT NULL,
  avatar_url VARCHAR(255) DEFAULT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS communication_record (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  source_type VARCHAR(16) NOT NULL,
  input_text TEXT DEFAULT NULL,
  asr_text TEXT DEFAULT NULL,
  normalized_text TEXT NOT NULL,
  scene_code VARCHAR(32) DEFAULT NULL,
  scene_source VARCHAR(16) NOT NULL DEFAULT 'auto',
  relation_code VARCHAR(32) DEFAULT NULL,
  goal_code VARCHAR(32) DEFAULT NULL,
  tone_tags JSON DEFAULT NULL,
  emotion_level TINYINT NOT NULL DEFAULT 0,
  provider_code VARCHAR(32) DEFAULT NULL,
  model_name VARCHAR(64) DEFAULT NULL,
  prompt_version VARCHAR(32) DEFAULT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'success',
  favorite TINYINT NOT NULL DEFAULT 0,
  selected_variant_type VARCHAR(32) DEFAULT NULL,
  extra_meta JSON DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS communication_variant (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  record_id BIGINT NOT NULL,
  variant_type VARCHAR(32) NOT NULL,
  title VARCHAR(32) NOT NULL,
  content TEXT NOT NULL,
  style_tags JSON DEFAULT NULL,
  sort_order TINYINT NOT NULL DEFAULT 1,
  tts_media_id BIGINT DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS media_asset (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  record_id BIGINT DEFAULT NULL,
  variant_id BIGINT DEFAULT NULL,
  asset_type VARCHAR(16) NOT NULL,
  storage_provider VARCHAR(32) NOT NULL,
  bucket_name VARCHAR(64) DEFAULT NULL,
  object_key VARCHAR(255) NOT NULL,
  file_url VARCHAR(512) NOT NULL,
  local_file_path VARCHAR(1024) DEFAULT NULL,
  mime_type VARCHAR(64) DEFAULT NULL,
  duration_ms INT DEFAULT 0,
  size_bytes BIGINT DEFAULT 0,
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_feedback (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  record_id BIGINT NOT NULL,
  variant_type VARCHAR(32) DEFAULT NULL,
  action_type VARCHAR(32) NOT NULL,
  score TINYINT DEFAULT NULL,
  comment_text VARCHAR(255) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
